name: ClearAllInventories
main: us.ryanleonard.clearall.ClearAllInventories
version: 0.1

commands:
  clearAllInventories:
    description: Clears the inventory of all players
    usage: /<command>
    permission: clearAllInventories.clearAll
    permission-message: You don't have <permission>